language: objective-c
osx_image: xcode8.2
xcode_workspace: Project Altis.xcworkspace
xcode_sheme: Project Altis
before_install:
  - pod repo update
  - pod install

script:
  = xcodebuild -workspace "Project Altis.xcworkspace" -scheme "Project Altis" -sdk macosx clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
