language: objective-c
osx_image: xcode8.2
xcode_workspace: "Project Altis.xcworkspace"
xcode_sheme: "travis"
before_install:
  - pod repo update --silent
  - pod install

script:
  - xcodebuild -workspace "Project Altis.xcworkspace" -scheme "travis" -sdk macosx clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
